version: "3.8"

services:
    # customerservice:
    #     build:
    #         context: ./CustomerService/CustomerService
    #         dockerfile: Dockerfile
    #     ports:
    #         - "5001:80"
    #     depends_on:
    #         - customersql
    #         - rabbitmq
    #     environment:
    #         - ConnectionStrings__CustomerDbContext=Server=customersql;Database=CustomerDB;User=sa;Password=Your_password123;TrustServerCertificate=True
    #         - RabbitMQ__HostName=rabbitmq

    orderservice:
        build:
            context: ./OrderService
            dockerfile: OrderService/Dockerfile
        ports:
            - "5002:80"
        depends_on:
            - ordersql
            - rabbitmq
        environment:
            - ConnectionStrings__OrderDbContext=Server=ordersql;Database=OrderDB;User=sa;Password=Your_password123;TrustServerCertificate=True
            - RabbitMQ__HostName=rabbitmq

    # paymentservice:
    #     build:
    #         context: ./PaymentService/PaymentService
    #         dockerfile: Dockerfile
    #     ports:
    #         - "5003:80"
    #     depends_on:
    #         - paymentsql
    #         - rabbitmq
    #     environment:
    #         - ConnectionStrings__PaymentDbContext=Server=paymentsql;Database=PaymentDB;User=sa;Password=Your_password123;TrustServerCertificate=True
    #         - RabbitMQ__HostName=rabbitmq

    # customersql:
    #     image: mcr.microsoft.com/mssql/server:2019-latest
    #     environment:
    #         SA_PASSWORD: "Your_password123"
    #         ACCEPT_EULA: "Y"
    #     ports:
    #         - "1434:1433"

    ordersql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1435:1433"

    # paymentsql:
    #     image: mcr.microsoft.com/mssql/server:2019-latest
    #     environment:
    #         SA_PASSWORD: "Your_password123"
    #         ACCEPT_EULA: "Y"
    #     ports:
    #         - "1436:1433"

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672" # RabbitMQ Management Console
            - "5672:5672" # RabbitMQ Server
