services:
    paymentservice:
        build:
            context: ./PaymentService
            dockerfile: PaymentService/Dockerfile
        container_name: paymentservice
        ports:
            - "5001:80"
        depends_on:
            - rabbitmq
        environment:
            - RabbitMQ__HostName=rabbitmq

    orderservice:
        build:
            context: ./OrderService
            dockerfile: OrderService/Dockerfile
        container_name: orderservice
        ports:
            - "5002:80"
        depends_on:
            - ordersql
            - rabbitmq
        environment:
            - ConnectionStrings__OrderDbContext=Server=ordersql,1433;Database=OrderDB;User=sa;Password=Your_password123;TrustServerCertificate=True
            - RabbitMQ__HostName=rabbitmq

    ordersql:
        container_name: ordersql
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: Your_password123
            ACCEPT_EULA: "Y"
        ports:
            - "1435:1433"

    rabbitmq:
        container_name: rabbitmq
        image: masstransit/rabbitmq
        ports:
            - "15672:15672" # RabbitMQ Management Console
            - "5672:5672" # RabbitMQ Server
