version: '3.4'

services:
  customerservice:
    image: ${DOCKER_REGISTRY-}customerservice
    build:
      context: .
      dockerfile: CustomerService/Dockerfile
    ports:
    - "80:80"
    - "443:443"

  rabbitmq:
    image: "masstransit/rabbitmq"
    hostname: "localhost"
    ports: 
    - "15672:15672"
    - "5672:5672"